# fly.toml app configuration file generated for sinreversa-empty-night-9705 on 2025-07-09T02:51:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sinreversa-empty-night-9705'
primary_region = 'scl'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'php artisan migrate --force'

[env]
  DB_CONNECTION = 'mysql'
  DB_DATABASE = 'tu-db-name'
  DB_HOST = 'tu-db-host'
  DB_PASSWORD = 'tu-db-password'
  DB_PORT = '3306'
  DB_USERNAME = 'tu-db-user'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
